apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-nginx
  labels:
    app: phpfpm-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-nginx
  template:
    metadata:
      labels:
        app: phpfpm-nginx    
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: {}
    
        # Add the ConfigMap we declared above as a volume for the pod
        - name: nginx-config-volume
          configMap:
            name: nginx-config

      containers:
        # Our PHP-FPM application
        - image: docker_image:1.0.0
          name: app # your pod app name
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
    
    # Our nginx container, which uses the configuration declared above,
    # along with the files shared with the PHP-FPM app.
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf